spring:
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/test3 
    username: root 
    password: password 
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m

server:
  port: 8080

  
 
  sql:
    init:
      mode: always
